"""added fields to ticket

Revision ID: 5a6815ab8bfd
Revises: 9fe22654b5d8
Create Date: 2026-04-09 16:08:45.569194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a6815ab8bfd'
down_revision: Union[str, Sequence[str], None] = '9fe22654b5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('ticket', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.add_column('ticket', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ticket_category_id'), 'ticket', ['category_id'], unique=False)
    op.create_index(op.f('ix_ticket_company_id'), 'ticket', ['company_id'], unique=False)
    op.create_index(op.f('ix_ticket_subcategory_id'), 'ticket', ['subcategory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_subcategory_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_company_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_category_id'), table_name='ticket')
    op.drop_column('ticket', 'company_id')
    op.drop_column('ticket', 'subcategory_id')
    op.drop_column('ticket', 'category_id')
    # ### end Alembic commands ###
