"""add_fk_cascade_to_subcategoryteam

Revision ID: 7a3fe1167646
Revises: 9e4b4918d0e0
Create Date: 2026-03-10 11:24:14.108846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a3fe1167646'
down_revision: Union[str, Sequence[str], None] = '9e4b4918d0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'subcategoryteam', 'subcategory', ['sub_category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subcategoryteam', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategoryteam', type_='foreignkey')
    op.drop_constraint(None, 'subcategoryteam', type_='foreignkey')
    # ### end Alembic commands ###
