"""assigned team droped

Revision ID: 7bd6395a5bd2
Revises: 42285897e1cf
Create Date: 2026-03-08 11:35:27.231199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7bd6395a5bd2'
down_revision: Union[str, Sequence[str], None] = '42285897e1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'assigned_team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('assigned_team', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
