"""client visibility field added

Revision ID: 9fe22654b5d8
Revises: d224bb9201cd
Create Date: 2026-04-09 14:20:30.570596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fe22654b5d8'
down_revision: Union[str, Sequence[str], None] = 'd224bb9201cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategoryteam', sa.Column('is_client_visible', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategoryteam', 'is_client_visible')
    # ### end Alembic commands ###
