"""team_name refactored to company_id

Revision ID: d224bb9201cd
Revises: 7a3fe1167646
Create Date: 2026-04-09 12:46:26.638833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd224bb9201cd'
down_revision: Union[str, Sequence[str], None] = '7a3fe1167646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategoryteam', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_column('subcategoryteam', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategoryteam', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subcategoryteam', 'company_id')
    # ### end Alembic commands ###
